apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pok8s
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      namespace: pok8s
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "dev"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  namespace: pok8s
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000