apiVersion: v1
kind: Service
metadata:
  namespace: pok8s
  name: pok8s-server-nodeport
spec:
  type: NodePort
  selector:
    app: pok8s-server
  ports:
    - name: pok8s-server
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010