apiVersion: v1
kind: Service
metadata:
  namespace: helm
  name: helm-redis-ip
spec:
  type: ClusterIP
  selector:
    app: helm-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379