apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pok8s
  name: pok8s-server
  labels:
    app: pok8s-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pok8s-server
  template:
    metadata:
      namespace: pok8s
      labels:
        app: pok8s-server
    spec:
      containers:
        - name: pok8s-server
          image: server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "dev"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: pok8s-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: pok8s-configmap
                  key: REDIS_PORT