namespace: helm

port: 8080

name: helm-unhealthy-server
autoscaling:
  replicas: 3

image:
  repository: smlinux/unhealthy
  pullPolicy: IfNotPresent

livenessProbe:
  path: /
  initialDelaySeconds: 3
  periodSeconds: 2
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 2
readinessProbe:
  path: /
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 2