apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helm
  name: helm-server
  labels:
    app: helm-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helm-server
  template:
    metadata:
      namespace: helm
      labels:
        app: helm-server
    spec:
      containers:
        - name: helm-server
          image: server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "dev"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: helm-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: helm-configmap
                  key: REDIS_PORT