apiVersion: v1
kind: Service
metadata:
  namespace: helm
  name: helm-server-nodeport
spec:
  type: NodePort
  selector:
    app: helm-server
  ports:
    - name: helm-server
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30020