namespace: helm
env: dev

port: 3000
nodePort: 30020

name: helm-server
autoscaling:
  replicas: 3

image:
  tag: latest
  pullPolicy: IfNotPresent

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3