apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: server-nodeport
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010